/*-
 * WSDL stubs for:  http://dcsquares.c99.org/2.0/SOAP/scores.php?wsdl
 *   Generated by:  samsteele
 *           Date:  Sun Apr 17 20:21:41 2005
 *        Emitter:  Objective-C
 */

#import "Scores.h"

/*-
 *   Method Name:  getHighScore
 * Documentation:  <no documentation>
 */
@implementation getHighScore
- (void) setParameters:(SInt32) in_userID
{
    id _paramValues[] = {    
        [NSNumber numberWithInt: in_userID],        
    };    
    NSString* _paramNames[] = {    
        @"userID",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"score"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dcsquares.c99.org/2.0/SOAP/scores.php"            
                 methodName: @"getHighScore"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:Scores#scores#getHighScore"            
            methodNamespace: @"urn:Scores"            
        ];        
}

@end; /* getHighScore */


/*-
 *   Method Name:  submitScore
 * Documentation:  <no documentation>
 */
@implementation submitScore
- (void) setParameters:(NSString*) in_username in_password:(NSString*) in_password in_score:(SInt32) in_score in_combo:(SInt32) in_combo in_time:(double) in_time in_platform:(NSString*) in_platform
{
    id _paramValues[] = {    
        in_username,        
        in_password,        
        [NSNumber numberWithInt: in_score],        
        [NSNumber numberWithInt: in_combo],        
        [NSNumber numberWithDouble: in_time],        
        in_platform,        
    };    
    NSString* _paramNames[] = {    
        @"username",        
        @"password",        
        @"score",        
        @"combo",        
        @"time",        
        @"platform",        
    };    
    [super setParameters:6 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"result"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dcsquares.c99.org/2.0/SOAP/scores.php"            
                 methodName: @"submitScore"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:Scores#scores#submitScore"            
            methodNamespace: @"urn:Scores"            
        ];        
}

@end; /* submitScore */


/*-
 *   Method Name:  getScores
 * Documentation:  <no documentation>
 */
@implementation getScores
- (void) setParameters:(NSString*) in_startDate in_endDate:(NSString*) in_endDate in_count:(NSString*) in_count
{
    id _paramValues[] = {    
        in_startDate,        
        in_endDate,        
        in_count,        
    };    
    NSString* _paramNames[] = {    
        @"startDate",        
        @"endDate",        
        @"count",        
    };    
    [super setParameters:3 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"scores"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dcsquares.c99.org/2.0/SOAP/scores.php"            
                 methodName: @"getScores"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:Scores#scores#getScores"            
            methodNamespace: @"urn:Scores"            
        ];        
}

@end; /* getScores */


/*-
 *   Method Name:  getRank
 * Documentation:  <no documentation>
 */
@implementation getRank
- (void) setParameters:(SInt32) in_userID
{
    id _paramValues[] = {    
        [NSNumber numberWithInt: in_userID],        
    };    
    NSString* _paramNames[] = {    
        @"userID",        
    };    
    [super setParameters:1 values: _paramValues names: _paramNames];    
}

- (id) resultValue
{
    return [[super getResultDictionary] objectForKey: @"rank"];    
}

- (WSMethodInvocationRef) genCreateInvocationRef
{
    return [self createInvocationRef    
               /*endpoint*/: @"http://dcsquares.c99.org/2.0/SOAP/scores.php"            
                 methodName: @"getRank"            
                 protocol: (NSString*) kWSSOAP2001Protocol            
                      style: (NSString*) kWSSOAPStyleRPC            
                 soapAction: @"urn:Scores#scores#getRank"            
            methodNamespace: @"urn:Scores"            
        ];        
}

@end; /* getRank */



@implementation ScoresService

+ (id) getRank:(SInt32) in_userID
{
    id result = NULL;    
    getRank* _invocation = [[getRank alloc] init];    
    [_invocation setParameters: in_userID];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) getHighScore:(SInt32) in_userID
{
    id result = NULL;    
    getHighScore* _invocation = [[getHighScore alloc] init];    
    [_invocation setParameters: in_userID];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) submitScore:(NSString*) in_username in_password:(NSString*) in_password in_score:(SInt32) in_score in_combo:(SInt32) in_combo in_time:(double) in_time in_platform:(NSString*) in_platform
{
    id result = NULL;    
    submitScore* _invocation = [[submitScore alloc] init];    
    [_invocation setParameters: in_username in_password:in_password in_score:in_score in_combo:in_combo in_time:in_time in_platform:in_platform];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}


+ (id) getScores:(NSString*) in_startDate in_endDate:(NSString*) in_endDate in_count:(NSString*) in_count
{
    id result = NULL;    
    getScores* _invocation = [[getScores alloc] init];    
    [_invocation setParameters: in_startDate in_endDate:in_endDate in_count:in_count];    
    result = [[_invocation resultValue] retain];    
    [_invocation release];    
    return result;    
}



@end;


/*-
 * End of WSDL document at http://dcsquares.c99.org/2.0/SOAP/scores.php?wsdl
 */
